node {
     checkout scm
	
	 docker.withRegistry('https://hub.docker.com/','docker_hub') {
	     def customImage = docker.build("vivek13s/app")
		 
		 /*Push the container to the custom Registry */
		 customImage.push()
	 }
}	 
